# Generated by Django 5.0.6 on 2026-05-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Hostel Out Main Gate', max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('location_type', models.CharField(choices=[('0', 'Gate In'), ('1', 'Gate Out'), ('2', 'Hostel Out'), ('3', 'Hostel In')], max_length=2)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
