# Generated by Django 5.0.6 on 2026-05-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essl_app', '0002_biometricdevice_attendancelog_device_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
