# Generated by Django 5.0.6 on 2026-05-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essl_app', '0003_biometricdevice_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricdevice',
            name='serial_number',
        ),
    ]
