# Generated by Django 5.2.4 on 2025-07-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('year', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4')], max_length=2)),
                ('branch', models.CharField(choices=[('PUC', 'PUC'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('EEE', 'EEE'), ('ME', 'ME'), ('MME', 'MME'), ('CE', 'CE'), ('CHE', 'CHE'), ('AI&ML', 'AI&ML')], max_length=10)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
