# Generated by Django 5.2.4 on 2025-07-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('leave', 'Leave'), ('outing', 'Outing')], default='present', max_length=10),
        ),
    ]
