# Generated by Django 5.0.6 on 2025-07-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_remove_student_room_number_student_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(help_text='Reason for leave/outing.')),
                ('out_time', models.DateTimeField(blank=True, help_text='Date and time student left.', null=True)),
                ('in_time', models.DateTimeField(blank=True, help_text='Date and time student returned.', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Any additional remarks.', null=True)),
                ('approved', models.BooleanField(default=False, help_text='Was this leave approved?')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='hostel_app.student')),
            ],
            options={
                'ordering': ['-date', '-out_time'],
            },
        ),
    ]
