# Generated by Django 5.0.6 on 2025-07-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0004_leaveapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='approved',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status of the leave application (Pending, Approved, Rejected).', max_length=10),
        ),
        migrations.CreateModel(
            name='StudentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, help_text='Previous status of the student.', max_length=10, null=True)),
                ('new_status', models.CharField(help_text='New status of the student.', max_length=10)),
                ('change_timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time of the status change.')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='hostel_app.student')),
            ],
            options={
                'ordering': ['-change_timestamp'],
            },
        ),
    ]
