# Generated by Django 5.0.6 on 2025-07-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0005_remove_leaveapplication_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstatuslog',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='studentstatuslog',
            name='old_status',
        ),
        migrations.AddField(
            model_name='studentstatuslog',
            name='current_status',
            field=models.CharField(choices=[('present', 'Present'), ('leave', 'Leave'), ('outing', 'Outing')], default='present', help_text='The status the student changed to.', max_length=10),
            preserve_default=False,
        ),
    ]
