# Generated by Django 5.0.6 on 2025-07-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0006_remove_studentstatuslog_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('viewer', 'Viewer'), ('editor', 'Editor')], default='student', help_text="Defines the user's access level (student, viewer, editor).", max_length=10),
        ),
    ]
