# Generated by Django 5.0.6 on 2025-07-30 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0007_student_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='qr_generated',
            field=models.BooleanField(default=False, help_text='True if a QR code has been generated for this approved leave.'),
        ),
        migrations.AddField(
            model_name='studentstatuslog',
            name='log_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('qr_scan', 'QR Scan')], default='manual', help_text='Indicates if the status change was manual or via QR scan.', max_length=10),
        ),
        migrations.AddField(
            model_name='studentstatuslog',
            name='scanned_device_info',
            field=models.CharField(blank=True, help_text='Information about the device that scanned the QR (e.g., IP, user-agent).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentstatuslog',
            name='scanned_location',
            field=models.CharField(blank=True, help_text='Location from where the QR was scanned (if available in payload/scan).', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LeaveQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the QR code payload (nonce).', unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this QR code was generated/rotated.')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when this QR code becomes invalid.')),
                ('is_used', models.BooleanField(default=False, help_text='True if this QR code has been successfully used for a log entry.')),
                ('location_id', models.CharField(blank=True, help_text='Optional: ID of the location where this QR code is valid.', max_length=50, null=True)),
                ('leave_application', models.OneToOneField(help_text='The leave application associated with this QR code.', on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='hostel_app.leaveapplication')),
            ],
            options={
                'verbose_name': 'Leave QR Code',
                'verbose_name_plural': 'Leave QR Codes',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='studentstatuslog',
            name='qr_code_used',
            field=models.ForeignKey(blank=True, help_text='The Leave QR Code used to initiate this status change, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_app.leaveqrcode'),
        ),
    ]
