# Generated by Django 5.0.6 on 2025-07-30 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0008_leaveapplication_qr_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='qr_code',
            field=models.OneToOneField(blank=True, help_text='The generated QR code instance for this leave application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_application_reverse_relation', to='hostel_app.leaveqrcode'),
        ),
        migrations.AddField(
            model_name='leaveqrcode',
            name='qr_data',
            field=models.TextField(blank=True, help_text='The JWT token string encoded in the QR code for verification.', null=True),
        ),
        migrations.AlterField(
            model_name='leaveqrcode',
            name='leave_application',
            field=models.OneToOneField(help_text='The leave application associated with this QR code.', on_delete=django.db.models.deletion.CASCADE, related_name='associated_qr_code', to='hostel_app.leaveapplication'),
        ),
    ]
