# Generated by Django 5.0.6 on 2026-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0009_leaveapplication_qr_code_leaveqrcode_qr_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hostel',
            field=models.CharField(choices=[('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3'), ('K2', 'K2'), ('K3', 'K3'), ('K4', 'K4')], default='I1', max_length=5),
        ),
    ]
