# Generated by Django 5.0.6 on 2026-04-18 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0010_student_hostel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'ordering': ['-out_time']},
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='date',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='remarks',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='approval_of',
            field=models.CharField(blank=True, help_text='Optional: Name or role of the person who approved this.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('leave', 'Leave'), ('outing', 'Outing')], default='leave', help_text='Type of application: Leave or Outing.', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='in_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time student plans to return.'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='out_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time student plans to leave.'),
        ),
    ]
