# Generated by Django 5.0.6 on 2026-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0011_alter_leaveapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatuslog',
            name='log_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('qr_scan_exit', 'QR Scan (Exit)'), ('qr_scan_entry', 'QR Scan (Entry)'), ('qr_scan_exit_no_change', 'QR Scan (Exit - Status Unchanged)'), ('qr_scan_entry_no_change', 'QR Scan (Entry - Status Unchanged)')], default='manual', help_text='Indicates if the status change was manual or via QR scan.', max_length=50),
        ),
    ]
