# Generated by Django 5.0.6 on 2026-04-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0012_alter_studentstatuslog_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstatuslog',
            name='qr_code_used',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='qr_generated',
        ),
        migrations.RemoveField(
            model_name='studentstatuslog',
            name='scanned_device_info',
        ),
        migrations.RemoveField(
            model_name='studentstatuslog',
            name='scanned_location',
        ),
        migrations.AlterField(
            model_name='studentstatuslog',
            name='log_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('biometric', 'Biometric')], default='manual', help_text='Indicates if the status change was manual or via biometric scan.', max_length=50),
        ),
        migrations.DeleteModel(
            name='LeaveQRCode',
        ),
    ]
