# Generated by Django 5.0.6 on 2026-05-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0015_student_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='companion',
            field=models.ForeignKey(blank=True, help_text='The student whose parent is coming (for restricted group leave).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accompanied_leaves', to='hostel_app.student'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='parent_coming',
            field=models.BooleanField(default=False, help_text="Is the student's own parent coming to pick them up?"),
        ),
    ]
