# Generated by Django 6.0.5 on 2026-09-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0016_leaveapplication_companion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='caretaker_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='caretaker_verified_by',
            field=models.ForeignKey(blank=True, help_text="The caretaker who confirmed the student's ID before departure.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_departures', to='hostel_app.student'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='current_stage',
            field=models.CharField(choices=[('WARDEN', 'Pending Warden'), ('CARETAKER', 'Pending Caretaker'), ('CHIEF_WARDEN', 'Pending Chief Warden'), ('DSW', 'Pending DSW'), ('DEAN', 'Pending Dean'), ('AO', 'Pending AO Office'), ('DIRECTOR', 'Pending Director'), ('CARETAKER_VERIFICATION', 'Awaiting ID Verification'), ('CLEARED_FOR_DEPARTURE', 'Gate-Out Pending'), ('OUT', 'Outside Campus'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='WARDEN', help_text='Which authority the request is currently waiting on, or its post-approval departure/return stage.', max_length=30),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='email_error',
            field=models.TextField(blank=True, help_text='Last email send error, if email_status is FAILED.', null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='email_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='NOT_REQUIRED', max_length=15),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='gate_in_at',
            field=models.DateTimeField(blank=True, help_text="Biometric Gate-In punch recorded for this leave's return.", null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='gate_out_at',
            field=models.DateTimeField(blank=True, help_text='First biometric out-punch (Gate Out or Hostel Out) recorded for this leave.', null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='hostel_in_at',
            field=models.DateTimeField(blank=True, help_text="Biometric Hostel-In punch that completed this leave's return.", null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='letter_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='leave_letters/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('viewer', 'Viewer'), ('editor', 'Editor'), ('warden', 'Warden'), ('caretaker', 'Caretaker'), ('chief_warden', 'Chief Warden'), ('dsw', 'DSW'), ('dean', 'Dean'), ('ao', 'AO Office'), ('director', 'Director')], default='student', help_text="Defines the user's access level (student, viewer, editor).", max_length=15),
        ),
        migrations.CreateModel(
            name='LeaveApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(help_text='The stage this action was taken at.', max_length=30)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'ID Verified'), ('VERIFICATION_FAILED', 'ID Verification Failed'), ('GATE_OUT', 'Biometric Gate-Out'), ('GATE_IN', 'Biometric Gate-In'), ('HOSTEL_IN', 'Biometric Hostel-In'), ('LETTER_GENERATED', 'Letter Generated'), ('EMAIL_SENT', 'Email Sent'), ('EMAIL_FAILED', 'Email Failed')], max_length=25)),
                ('comment', models.TextField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The staff member who took this action (blank for system/biometric events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_actions_taken', to='hostel_app.student')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='hostel_app.leaveapplication')),
            ],
            options={
                'verbose_name_plural': 'Leave approval history',
                'ordering': ['timestamp'],
            },
        ),
    ]
