# Generated by Django 5.0.6 on 2025-07-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor__floor_number', 'room_number']},
        ),
    ]
