# Generated by Django 5.0.6 on 2025-07-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0002_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['floor_number']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number']},
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
