# Generated by Django 5.0.6 on 2026-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0003_alter_floor_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['hostel', 'floor_number']},
        ),
        migrations.AddField(
            model_name='floor',
            name='hostel',
            field=models.CharField(choices=[('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3'), ('K2', 'K2'), ('K3', 'K3'), ('K4', 'K4')], default='I1', max_length=5),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('hostel', 'floor_number')},
        ),
    ]
